#!/usr/bin/env bash

#update package lists and install Nginx
#sudo apt-get update
#sudo apt-get install -y nginx

# Get the hostname of the server
#hostname=$(hostname)

#configure Nginx custom response header
#cat <<EOF | sudo tee /etc/nginx/conf.d/custom_response_header.conf
#server {
#    listen 80 default_server;
#    listen [::]:80 default_server;

#    # Add custom response header
#    add_header X-served-By $hostname
#}
#EOF

# Test Nginx configuration
#sudo nginx -t

# Reload Nginx to apply changes
#sudo systemctl reload nginx

# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y
sudo echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
sudo echo "This is not a page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx start
