#!/usr/bin/env bash
# Loop through numbers 1 to 100
for i in {1..100}; do
  # Check for multiples and build output
  output=""
  if [[ $((i % 3)) -eq 0 ]]; then
    output+="Fizz"
  fi
  if [[ $((i % 5)) -eq 0 ]]; then
    output+="Buzz"
  fi

  # Print the output, either the number or FizzBuzz
  if [[ -z "$output" ]]; then
    echo "$i"
  else
    echo "$output"
  fi
done






