#!/usr/bin/env bash
# Initialize a counter variable
i=1

# Use a while loop to iterate 10 times
while [[ $i -le 10 ]]; do
  if [[ $i -eq 9 ]]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  i=$((i + 1)) # Increment the counter
done
