#!/usr/bin/env bash
# Initialize counter
i=1

# Loop through numbers 1 to 10
while [[ $i -le 10 ]]; do
  if [[ $i -eq 4 ]]; then
    echo "Oh no, bad luck!"
  elif [[ $i -eq 8 ]]; then
    echo "Hurray, good luck!"
  else
    echo "Best School"
  fi

  # Increment counter
  ((i++))
done

