#!/usr/bin/env bash
# Loop through numbers 1 to 20
i=1
while [[ $i -le 20 ]]; do
  # Use a case statement to handle specific numbers
  case $i in
    4)
      echo "$i and bad luck from China"
      ;;
    9)
      echo "$i and bad luck from Japan"
      ;;
    17)
      echo "$i and bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac

  # Increment counter
  ((i++))
done
