#!/usr/bin/env bash
# Check if the file exists
if [[ -f "school" ]]; then
  echo "school file exists"

  # Check if the file is empty
  if [[ -z "$(cat school)" ]]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi

  # Check if the file is a regular file
  if [[ -e "school" ]]; then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi





